Error: call revert exception (method="test(string)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.4.0)
      at Logger.makeError (node_modules\@ethersproject\logger\src.ts\index.ts:213:28)
      at Logger.throwError (node_modules\@ethersproject\logger\src.ts\index.ts:225:20)
      at Interface.decodeFunctionResult (node_modules\@ethersproject\abi\src.ts\interface.ts:425:23)
      at Contract.<anonymous> (node_modules\@ethersproject\contracts\src.ts\index.ts:332:44)
      at step (node_modules\@ethersproject\contracts\lib\index.js:48:23)
      at Object.next (node_modules\@ethersproject\contracts\lib\index.js:29:53)
      at fulfilled (node_modules\@ethersproject\contracts\lib\index.js:20:58)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at runNextTicks (internal/process/task_queues.js:64:3)
      at listOnTimeout (internal/timers.js:526:9)
      at processTimers (internal/timers.js:500:7)
